@startuml pert8
autonumber "<b> ." 
actor user
participant "Menu" as M
participant "Pilih Menu" as pil
participant "Ferari" as Ferari
participant "Lambo" as Lambo
participant "Jumlah" as jmlh
participant "Total" as tot
participant "Exit" as X

user --> M: Tampilkan Menu Utama
M --> pil: Pilihan Menu 1 Atau 2, Pilih Ferari Atau Lambo
pil --> Ferari: Menampilkan Profile Ferari
Ferari --> jmlh: Masukkan Jumlah Profil Ferari
jmlh --> tot: Print
M --> tot: Kembali Ke Menu
pil --> Lambo: Menampilkan Jumlah Profil Lambo
jmlh --> tot: print
tot --> X: Jika Pilihan Exit
M <-- tot: Kembali Ke Menu
@enduml